# Handling The Data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("employees.csv")

In [4]:
df.head()

      name age   department salary       city score
0   Nirmal  35  Engineering    NaN   Lalitpur    65
1   Pratik  40        Sales  44071    Hetauda    79
2  Chetana  40           HR  47395     Dharan    88
3    Anish  43      Support  44671  Bhaktapur    92
4   Januka  35      Support  54817    Pokhara    88

In [5]:
# dataset Explore
df.shape

(266, 6)

In [9]:
df.describe()

         name  age department salary     city score
count     266  250        266    242      256   253
unique     66   30          6    236       16    36
top     Eliza   42    Finance  72222  Hetauda    88
freq       12   17         52      2       42    14

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        266 non-null    object
 1   age         250 non-null    object
 2   department  266 non-null    object
 3   salary      242 non-null    object
 4   city        256 non-null    object
 5   score       253 non-null    object
dtypes: object(6)
memory usage: 12.6+ KB

In [10]:
df.columns

Index(['name', 'age', 'department', 'salary', 'city', 'score'], dtype='object')

In [11]:
df.dtypes

name          object
age           object
department    object
salary        object
city          object
score         object
dtype: object

In [12]:
df["age"].unique()

array(['35', '40', '43', '21', '22', '23', '32', '39', '41 yrs', '33',
       '27', '41', '24', '30', '31', '45', '37', '34', nan, '42', '29',
       '44', '26', '36', '28', '38', '39 yrs', '25', '43 yrs', '130',
       '35 yrs'], dtype=object)

In [13]:
df["age_clean"] = df["age"].astype(float)

ValueError: could not convert string to float: '41 yrs'

In [15]:
df["age"] = df["age"].astype(str)

In [18]:
df.dtypes

name          object
age           object
department    object
salary        object
city          object
score         object
dtype: object

In [19]:
df['age'] = df['age'].astype(str).str.replace(' yrs', '')

In [20]:
df["age"].unique()

array(['35', '40', '43', '21', '22', '23', '32', '39', '41', '33', '27',
       '24', '30', '31', '45', '37', '34', 'nan', '42', '29', '44', '26',
       '36', '28', '38', '25', '130'], dtype=object)

In [30]:
df['age'] = df['age'].astype(float)

In [25]:
df.dtypes

name           object
age           float64
department     object
salary         object
city           object
score          object
dtype: object

In [27]:
df["age"].unique()

array([ 35.,  40.,  43.,  21.,  22.,  23.,  32.,  39.,  41.,  33.,  27.,
        24.,  30.,  31.,  45.,  37.,  34.,  nan,  42.,  29.,  44.,  26.,
        36.,  28.,  38.,  25., 130.])

In [32]:
df["age"] = pd.to_numeric(df['age'], errors='coerce').astype('Int64')

In [33]:
df.dtypes

name          object
age            Int64
department    object
salary        object
city          object
score         object
dtype: object

In [34]:
df["salary"].unique()

array([nan, '44071', '47395', '44671', '54817', '47276', '54418', '51011',
       '74036', '72222', '61196', '59900', '45344', '73763', 'Rs.71713',
       '78034', '40763', '53544', '54066', '49152', '68670', '63264',
       '42340', '46207', '74210', '54051', '59064', '69164', '71559',
       '53117', '43169', '-40679', '71096', '48286', '45554', '72306',
       '69945', '44993', '42286', '53865', '46199', '50372', '71332',
       '79870', '40887', '63964', '70972', '46427', '63563', '57293',
       '44459', '56762', '44451', '59883', '56044', '65024', '52185',
       '43916', '42946', '65118', '59303', '45685', '54699', '55132',
       '54240', '42137', '51002', '54605', '52794', '58839', '40018',
       '45090', '52079', '64806', '70191', '45717', '55929', '64311',
       '70559', '46724', '67877', '58635', '59856', '47406', '-52860',
       '44335', '53825', '64295', '41427', '50801', '72629', '51891',
       '47784', '55910', '79675', '69693', '45093', '57394', '51762',
       '54839', '54239', '57130', '48914', '46408', '71382', '51074',
       'Rs.41096', '59914', '67248', '43157', '67382', '68146', '46532',
       '61571', '42640', '54726', '51145', '49506', '53498', '66318',
       '58481', '58882', '60540', '65181', '60428', '55868', '46989',
       '60862', '51482', '49099', '49802', '43485', '55337', '69142',
       '45260', '57083', '70273', '57736', '61045', '53060', '47685',
       '49634', '71895', '73377', '48446', '47957', '59007', '70123',
       '68328', '66136', '47354', '56626', '58927', '48067', '61825',
       '55022', '48124', '46259', '40883', '53381', '44887', '52857',
       '57160', '38517', '60456', '51990', '52994', '48681', '67794',
       '55623', '44473', '62322', '54650', '48770', '45119', '51861',
       '48893', '54181', '76294', '72171', '42783', '78847', '66582',
       '57449', '55394', '54490', 'Rs.71701', '48076', '56967', '54972',
       '67615', '63922', '48369', '44683', '58111', '55081', '38212',
       'Rs.55582', '50176', '55780', '43729', '48754', '50748',
       'Rs.44805', '73472', '59913', '49055', '60482', '61540', '46002',
       '44147', '53121', '57661', '40791', '57753', '53989', '67024',
       '44245', '63319', '46204', '68014', '69554', '52182', '63012',
       '43753', '68288', '43789', '52092', '49850', '58398', '-66400',
       '47540', '41795', '60565', '45261', '47008', '59877'], dtype=object)

In [35]:
df.describe()

            age
count     250.0
mean      34.54
std    11.22964
min        21.0
25%       28.25
50%        34.0
75%        40.0
max       130.0

In [36]:
df["salary"] = pd.to_numeric(df['salary'], errors='coerce').astype('Int64')

In [37]:
df.dtypes

name          object
age            Int64
department    object
salary         Int64
city          object
score         object
dtype: object

In [38]:
# Filetering the Data
df[df["age"] > 25]

           name  age   department  salary       city score
0        Nirmal   35  Engineering    <NA>   Lalitpur    65
1        Pratik   40        Sales   44071    Hetauda    79
2       Chetana   40           HR   47395     Dharan    88
3         Anish   43      Support   44671  Bhaktapur    92
4        Januka   35      Support   54817    Pokhara    88
..          ...  ...          ...     ...        ...   ...
259       Meera   42  Engineering  -66400  Bhaktapur    67
261  Chiranjivi   33           HR   41795  Kathmandu    73
262       Rajan   30    Marketing   60565     Dharan   NaN
264       Niraj   40        Sales   47008     Butwal    70
265      Jeevan   43        Sales   59877  Kathmandu    83

[206 rows x 6 columns]

In [41]:
df[df["salary"] > 55000]

       name  age   department  salary        city score
8     Eliza   32  Engineering   74036      Butwal    63
9     Nisha   39  Engineering   72222      Dharan    85
10    Ishan   41      Finance   61196      Butwal    63
11   Bishal   39      Finance   59900    Lalitpur    71
14    Laxmi   33  Engineering   73763      Butwal    76
..      ...  ...          ...     ...         ...   ...
252      Om   21      Finance   63012  Biratnagar    74
254   Gopal   22      Finance   68288   kathmandu    93
258  Fatima   43    Marketing   58398    Lalitpur    83
262   Rajan   30    Marketing   60565      Dharan   NaN
265  Jeevan   43        Sales   59877   Kathmandu    83

[108 rows x 6 columns]

In [44]:
df[(df["age"] > 25) &
   (df["salary"] > 55000)]

        name  age   department  salary       city score
8      Eliza   32  Engineering   74036     Butwal    63
9      Nisha   39  Engineering   72222     Dharan    85
10     Ishan   41      Finance   61196     Butwal    63
11    Bishal   39      Finance   59900   Lalitpur    71
14     Laxmi   33  Engineering   73763     Butwal    76
..       ...  ...          ...     ...        ...   ...
249  Fulmaya   38      Finance   68014  Kathmandu    67
250   Ganesh   26      Finance   69554    Hetauda    76
258   Fatima   43    Marketing   58398   Lalitpur    83
262    Rajan   30    Marketing   60565     Dharan   NaN
265   Jeevan   43        Sales   59877  Kathmandu    83

[87 rows x 6 columns]

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        266 non-null    object
 1   age         250 non-null    Int64
 2   department  266 non-null    object
 3   salary      237 non-null    Int64
 4   city        256 non-null    object
 5   score       253 non-null    object
dtypes: Int64(2), object(4)
memory usage: 13.1+ KB

In [46]:
df.isnull()

      name    age  department  salary   city  score
0    False  False       False    True  False  False
1    False  False       False   False  False  False
2    False  False       False   False  False  False
3    False  False       False   False  False  False
4    False  False       False   False  False  False
..     ...    ...         ...     ...    ...    ...
261  False  False       False   False  False  False
262  False  False       False   False  False   True
263  False  False       False   False   True  False
264  False  False       False   False  False  False
265  False  False       False   False  False  False

[266 rows x 6 columns]

In [47]:
df.isnull().sum()

name           0
age           16
department     0
salary        29
city          10
score         13
dtype: int64

In [49]:
# Drop
df = df.dropna(subset=['city'])

In [50]:
df.isnull().sum()

name           0
age           15
department     0
salary        28
city           0
score         13
dtype: int64

In [51]:
df.shape

(256, 6)

In [53]:
df['age'] = df['age'].fillna(df['age'].median())

/tmp/ipykernel_1381/3541415502.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age'] = df['age'].fillna(df['age'].median())

In [54]:
df.isnull().sum()

name           0
age            0
department     0
salary        28
city           0
score         13
dtype: int64

In [56]:
df.shape

(256, 6)

In [57]:
df = df.drop('score', axis = 1)

In [58]:
df.shape

(256, 5)