# Pandas

In [1]:
import pandas as pd

In [4]:
# Create a Series
data = [10, 20, 30, 40]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
s = pd.Series(data, index=['a', 'b', 'c', 'e'])
print(s)

a    10
b    20
c    30
e    40
dtype: int64

In [7]:
# create a DataFrame

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "San Francisco", "Los Angeles"]
}

df = pd.DataFrame(data)

print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [8]:
print(type(s))
print(type(df))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [13]:
# Check object type
# isinstance(s, pd.Series)
isinstance(df, pd.DataFrame)

True

In [14]:
# Loading Data From files(csv)
df = pd.read_csv("employees.csv")

In [17]:
# Exploring A Dataset
df.head()

      name age   department salary       city score
0   Nirmal  35  Engineering    NaN   Lalitpur    65
1   Pratik  40        Sales  44071    Hetauda    79
2  Chetana  40           HR  47395     Dharan    88
3    Anish  43      Support  44671  Bhaktapur    92
4   Januka  35      Support  54817    Pokhara    88
5   Jeevan  21    Marketing  47276    Pokhara   NaN
6  Ashmita  22        Sales  54418  Kathmandu    84
7    Suman  23        Sales  51011     Butwal    84
8    Eliza  32  Engineering  74036     Butwal    63
9    Nisha  39  Engineering  72222     Dharan    85

In [16]:
df.tail()

           name age department salary       city score
261  Chiranjivi  33         HR  41795  Kathmandu    73
262       Rajan  30  Marketing  60565     Dharan   NaN
263    Chandani  23    Support  45261        NaN    75
264       Niraj  40      Sales  47008     Butwal    70
265      Jeevan  43      Sales  59877  Kathmandu    83

In [18]:
df.shape

(266, 6)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        266 non-null    object
 1   age         250 non-null    object
 2   department  266 non-null    object
 3   salary      242 non-null    object
 4   city        256 non-null    object
 5   score       253 non-null    object
dtypes: object(6)
memory usage: 12.6+ KB

In [20]:
df.describe() # statistical summary

         name  age department salary     city score
count     266  250        266    242      256   253
unique     66   30          6    236       16    36
top     Eliza   42    Finance  72222  Hetauda    88
freq       12   17         52      2       42    14

In [21]:
df.columns

Index(['name', 'age', 'department', 'salary', 'city', 'score'], dtype='object')

### column Extract

In [25]:
df["age"]

0      35
1      40
2      40
3      43
4      35
       ..
261    33
262    30
263    23
264    40
265    43
Name: age, Length: 266, dtype: object

In [23]:
df[["age","salary"]]

    age salary
0    35    NaN
1    40  44071
2    40  47395
3    43  44671
4    35  54817
..   ..    ...
261  33  41795
262  30  60565
263  23  45261
264  40  47008
265  43  59877

[266 rows x 2 columns]

### Selecting Row

In [26]:
df.loc[5]

name             Jeevan
age                  21
department    Marketing
salary            47276
city            Pokhara
score               NaN
Name: 5, dtype: object

### Filtering Data

In [28]:
df[df["age"] > 25]

TypeError: '>' not supported between instances of 'str' and 'int'

In [29]:
# NUll Data
df.isnull()

      name    age  department  salary   city  score
0    False  False       False    True  False  False
1    False  False       False   False  False  False
2    False  False       False   False  False  False
3    False  False       False   False  False  False
4    False  False       False   False  False  False
..     ...    ...         ...     ...    ...    ...
261  False  False       False   False  False  False
262  False  False       False   False  False   True
263  False  False       False   False   True  False
264  False  False       False   False  False  False
265  False  False       False   False  False  False

[266 rows x 6 columns]

In [30]:
df.isnull().sum()

name           0
age           16
department     0
salary        24
city          10
score         13
dtype: int64